### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by wesleyyee**

### CODE REVIEW

**Comment by wesleyyee** [comment]
@ryanmcdermott whats the process for publishing?

**Comment by ryanmcdermott** [comment]
Done!

**Comment by wesleyyee** [comment]
@ryanmcdermott any reason you can think of that would cause the installed package to throw an error but it runs find with your local build?

**Comment by ryanmcdermott** [comment]
What do you mean specifically? I don't understand what kind of error you're referring to.

**Comment by wesleyyee** [comment]
`Unsupported Primitive type 184` although there are no `TypeOperator` kinds in my ts. It runs fine for my local build

**Comment by ryanmcdermott** [comment]
I don't know what you mean by the installed package? If you npm install the latest version 0.2.2 it should have all of the latest changes.

**Comment by wesleyyee** [comment]
@ryanmcdermott ok installing 0.2.2 seems to have resolved the issue. On your initial bump it was 0.2.1 and that was giving me issues

**Pull request closed without merging**
