### PR TITLE
[Feat] Add support for default Apollo's Types

### PR DESCRIPTION
**Pull request by ignacioureta**
## Purpose
Adding support for Unions and Literals, both of which are used a lot on the `apollo:codegen` tool

This intends to include all the most common kinds that apollo codegen generates, so that by using them together we can create graphql mocks

### CODE REVIEW

**Comment by ignacioureta** [comment]
Signed the CLA!

**Comment by ignacioureta** [comment]
@ryanmcdermott travis is failing while doing `npm install`, but this PR didn't modified the `node_modules` or `package.json`. Any guidance on how to pass this?

**Comment by ryanmcdermott** [comment]
Thanks for your contribution! I'm trying to resolve the Travis CI build failure, I'll see if I can upgrade `node-sass` to get over the build issue where it doesn't find the proper release binary for their particular architecture on Travis CI machines.

**Comment by ryanmcdermott** [comment]
Ok it looks like the `node-sass` upgrade fixed it, can you rebase on `master` and update this PR?

**Comment by ignacioureta** [comment]
Sure, will send the changes during the day

**Comment by ryanmcdermott** [comment]
Thanks! Make sure to run `npm run format` on the files as this uses `clang-format` and not `prettier` (or any other formatter)

**Pull request closed without merging**
