### PR TITLE
Support Relative Imported Interfaces

### PR DESCRIPTION
**Pull request by 981377660LMT**
Hello! I have fixed the problem [References to objects between files fake as empty objects](https://github.com/google/intermock/issues/43) and passed ci and format.
I want to know your thoughts and will focus on this project.
Thanks!

### CODE REVIEW

**Comment by 981377660LMT** [comment]
@googlebot I fixed it.

**Comment by ryanmcdermott** [comment]
Thanks for your contribution, this is an absolutely fantastic start! One issue I see is that because this change uses file system modules that aren't available in a browser, then this would likely break the documentation site (google.github.io/intermock/)

Another approach is to pass a function (for discussion sake we can call it `resolution`) which does the resolution of file imports. Essentially this could live on the `Options` object passed into `mock`. https://github.com/google/intermock/blob/1cde0067e1098243016d5f96f42f4d1e3d0c0e97/src/cli/index.ts#L73

I think your code would not need too many modifications other than to move it to the `cli` file and then use `setImportExportSpecifier` as the resolution function, I believe. 
https://github.com/google/intermock/blob/master/src/cli/index.ts

What are your thoughts?

**Comment by 981377660LMT** [comment]
> Thanks for your contribution, this is an absolutely fantastic start! One issue I see is that because this change uses file system modules that aren't available in a browser, then this would likely break the documentation site (google.github.io/intermock/)
> 
> Another approach is to pass a function (for discussion sake we can call it `resolution`) which does the resolution of file imports. Essentially this could live on the `Options` object passed into `mock`.
> 
> https://github.com/google/intermock/blob/1cde0067e1098243016d5f96f42f4d1e3d0c0e97/src/cli/index.ts#L73
> 
> I think your code would not need too many modifications other than to move it to the `cli` file and then use `setImportExportSpecifier` as the resolution function, I believe.
> https://github.com/google/intermock/blob/master/src/cli/index.ts
> 
> What are your thoughts?


Don't worry. I have slightly edited webpack config to ignore fs in browser, ran **npm run docs-build** , opened index.html and checked the html worked well 😃.
And I changed tsconfig.ts's  lib option from "es2016" to "es2020" to support **String.prototype.matchAll**.
What do you think of it? I am looking forward to your reply 🚀.

**Comment by ryanmcdermott** [comment]
Thanks for modifying the webpack config! I should clarify my prior statement which is that I'm not sure how other users of this package are utilizing it and by adding a filesystem API to Intermock we will automatically make the module Node only by default. At the very least, it will require users to modify their own build settings, and it warrants bumping Intermock all the way to 1.0.

I'm leaning strongly towards keeping Intermock web compatible by default. While that necessitates the expense of bundling in an entire compiler, there could be lots of use cases out in the wild like that. An import resolver function passed in through the Options could be a happy middleground.

What are your thoughts given the opinion expressed above?

**Comment by 981377660LMT** [comment]
> Thanks for modifying the webpack config! I should clarify my prior statement which is that I'm not sure how other users of this package are utilizing it and by adding a filesystem API to Intermock we will automatically make the module Node only by default. At the very least, it will require users to modify their own build settings, and it warrants bumping Intermock all the way to 1.0.
> 
> I'm leaning strongly towards keeping Intermock web compatible by default. While that necessitates the expense of bundling in an entire compiler, there could be lots of use cases out in the wild like that. An import resolver function passed in through the Options could be a happy middleground.
> 
> What are your thoughts given the opinion expressed above?

I agree with you. Passing a function to the option is a compatible approach. I have added **resolveFileImports** in cli option and **importsResolver** in Intermock general options, and all work well.
What do you think of it? I am looking forward to your reply 🚀.

**Comment by ryanmcdermott** [comment]
Excellent work, thank you so much! One last administrative thing, can you resolve this? https://github.com/google/intermock/pull/58#issuecomment-891848287

**Comment by 981377660LMT** [comment]
@googlebot I fixed it.

**Comment by 981377660LMT** [comment]
force push your PR branch

> Excellent work, thank you so much! One last administrative thing, can you resolve this? [#58 (comment)](https://github.com/google/intermock/pull/58#issuecomment-891848287)

This has been solved by force-pushing the 981377660LMT:master branch from dd14d03 to 2958296 I checked .I changed the email used in git commit to ensure consistency with the one in CLA.

**Comment by ryanmcdermott** [comment]
Thank you again!

**Comment by fluffyspace** [comment]
For me that issue is still occurring, my intermock version is 0.2.5. Here's my test:

image

**Comment by mracette** [comment]
Was this every released? I see the change in the source but not in version `0.2.5`

**Comment by siosio34** [comment]
@ryanmcdermott @fluffyspace  
Has this version been released? If I still import type in 0.2.5 it comes out as an empty object.

**Pull request merged**
