### PR TITLE
support type literal #6

### PR DESCRIPTION
**Pull request by kahirokunn**
https://github.com/google/intermock/issues/6

### CODE REVIEW

**Comment by kahirokunn** [comment]
@ryanmcdermott How about this pull request ?

**Comment by ryanmcdermott** [comment]
Sorry for the delay! I've had limited time because of the current situation with CoVid

**Comment by kahirokunn** [comment]
I see.
Just take care😔

**Comment by ryanmcdermott** [comment]
Thanks for your great work! 🎉

**Comment by ryanmcdermott** [comment]
I won't be able to update the NPM package for a while since I am work from home given the CoVid-19 pandemic. I do not have access to my corporate workstation, and I need to be in its physical presence in order to run a security protocol to update NPM. Sorry for the delay.

**Comment by kahirokunn** [comment]
I see😷
Just take care and be careful your health🙏
Sorry for I sent to you remind message😫

**Pull request merged**
